/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Annija Bodniece (https://sketchfab.com/annijaBodniece)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/egyptian-boat-builder-22ea8cb1b4f349699bda1aecdbd33415
Title: Egyptian boat builder
*/

import { useRef , useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import {useFrame , useThree} from '@react-three/fiber'
import {a} from '@react-spring/three'
import islandScene from "../assets/3d/island.glb";

const Island = (props) => {
  const islandRef = useRef()
  const { nodes, materials } = useGLTF(islandScene)
  // const { actions } = useAnimations(animations)
  return (
    <a.group ref={islandRef} {...props}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="81d01e01666745dd8164833222b80d84fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="pPyramid1" position={[-2.312, -162.744, -46.6]}>
                  <mesh
                    name="pPyramid1_lambert1_0"
                    
                    
                    geometry={nodes.pPyramid1_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="pSphere1" position={[-2.312, -162.744, -46.6]}>
                  <mesh
                    name="pSphere1_lambert1_0"
                    
                    
                    geometry={nodes.pSphere1_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="pDisc1" position={[-2.312, -162.744, -46.6]}>
                  <mesh
                    name="pDisc1_lambert1_0"
                    
                    
                    geometry={nodes.pDisc1_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="pPlane5" position={[-2.312, -162.744, -46.6]}>
                  <mesh
                    name="pPlane5_lambert1_0"
                    
                    
                    geometry={nodes.pPlane5_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="pTorus1" position={[-2.312, -162.744, -46.6]}>
                  <mesh
                    name="pTorus1_lambert1_0"
                    
                    
                    geometry={nodes.pTorus1_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="pCone1" position={[-2.312, -162.744, -46.6]}>
                  <mesh
                    name="pCone1_lambert1_0"
                    
                    
                    geometry={nodes.pCone1_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="pDisc2" position={[-2.312, -162.744, -46.6]}>
                  <mesh
                    name="pDisc2_lambert1_0"
                    
                    
                    geometry={nodes.pDisc2_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="pCube133" position={[-2.312, -162.744, -46.6]}>
                  <mesh
                    name="pCube133_lambert1_0"
                    
                    
                    geometry={nodes.pCube133_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="polySurface144">
                  <group name="polySurface636" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface637" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface638" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface639" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface640" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface641" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface641_house_0"
                      
                      
                      geometry={nodes.polySurface641_house_0.geometry}
                      material={materials.house}
                    />
                  </group>
                  <group name="polySurface642" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface643" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface644" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface645" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface645_house_0"
                      
                      
                      geometry={nodes.polySurface645_house_0.geometry}
                      material={materials.house}
                    />
                  </group>
                  <group name="polySurface646" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface646_house_0"
                      
                      
                      geometry={nodes.polySurface646_house_0.geometry}
                      material={materials.house}
                    />
                  </group>
                  <group name="polySurface647" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface648" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface649" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface649_house_0"
                      
                      
                      geometry={nodes.polySurface649_house_0.geometry}
                      material={materials.house}
                    />
                  </group>
                  <group name="polySurface651" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface652" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface653" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface654" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface655" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface656" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface656_house_0"
                      
                      
                      geometry={nodes.polySurface656_house_0.geometry}
                      material={materials.house}
                    />
                  </group>
                  <group name="polySurface657" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface658" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface659" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface660" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface660_house_0"
                      
                      
                      geometry={nodes.polySurface660_house_0.geometry}
                      material={materials.house}
                    />
                  </group>
                  <group name="polySurface661" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface661_house_0"
                      
                      
                      geometry={nodes.polySurface661_house_0.geometry}
                      material={materials.house}
                    />
                  </group>
                  <group name="polySurface662" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface663" position={[-2.312, -162.744, -46.6]} />
                  <group name="polySurface664" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface664_house_0"
                      
                      
                      geometry={nodes.polySurface664_house_0.geometry}
                      material={materials.house}
                    />
                  </group>
                  <group name="polySurface692" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface692_house_0"
                      
                      
                      geometry={nodes.polySurface692_house_0.geometry}
                      material={materials.house}
                    />
                  </group>
                </group>
                <group name="polySurface146">
                  <group name="polySurface336" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface336_objects_0"
                      
                      
                      geometry={nodes.polySurface336_objects_0.geometry}
                      material={materials.objects}
                    />
                  </group>
                </group>
                <group name="polySurface337">
                  <group name="polySurface432" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface432_lambert3_0"
                      
                      
                      geometry={nodes.polySurface432_lambert3_0.geometry}
                      material={materials.lambert3}
                    />
                  </group>
                  <group name="polySurface575" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface575_lambert3_0"
                      
                      
                      geometry={nodes.polySurface575_lambert3_0.geometry}
                      material={materials.lambert3}
                    />
                  </group>
                </group>
                <group name="polySurface227" position={[0.141, -122.509, -114.455]}>
                  <mesh
                    name="polySurface227_aiStandardSurface16_0"
                    
                    
                    geometry={nodes.polySurface227_aiStandardSurface16_0.geometry}
                    material={materials.aiStandardSurface16}
                  />
                </group>
                <group name="polySurface615" position={[-2.312, -162.753, -46.6]}>
                  <mesh
                    name="polySurface615_aiStandardSurface11_0"
                    
                    
                    geometry={nodes.polySurface615_aiStandardSurface11_0.geometry}
                    material={materials.aiStandardSurface11}
                  />
                </group>
                <group name="pPlane6" position={[-2.312, -162.744, -46.6]}>
                  <mesh
                    name="pPlane6_lambert1_0"
                    
                    
                    geometry={nodes.pPlane6_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="polySurface818">
                  <group name="polySurface820" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface820_aiStandardSurface10_0"
                      
                      
                      geometry={nodes.polySurface820_aiStandardSurface10_0.geometry}
                      material={materials.aiStandardSurface10}
                    />
                  </group>
                </group>
                <group name="pTorus2" position={[-2.312, -162.744, -46.6]}>
                  <mesh
                    name="pTorus2_lambert1_0"
                    
                    
                    geometry={nodes.pTorus2_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                </group>
                <group name="polySurface721">
                  <group name="polySurface884" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface884_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface884_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface885" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface885_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface885_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface886" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface886_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface886_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface887" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface887_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface887_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface888" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface888_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface888_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface889" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface889_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface889_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface890" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface890_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface890_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface891" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface891_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface891_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface892" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface892_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface892_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface894" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface894_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface894_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface895" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface895_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface895_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface896" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface896_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface896_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                  <group name="polySurface897" position={[-2.312, -162.744, -46.6]}>
                    <mesh
                      name="polySurface897_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface897_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                </group>
                <group name="polySurface905" position={[-2.312, -162.744, -46.6]}>
                  <group name="polySurface1025">
                    <mesh
                      name="polySurface1025_aiStandardSurface10_0"
                      
                      
                      geometry={nodes.polySurface1025_aiStandardSurface10_0.geometry}
                      material={materials.aiStandardSurface10}
                    />
                  </group>
                  <group name="polySurface1030">
                    <mesh
                      name="polySurface1030_aiStandardSurface10_0"
                      
                      
                      geometry={nodes.polySurface1030_aiStandardSurface10_0.geometry}
                      material={materials.aiStandardSurface10}
                    />
                  </group>
                  <group name="polySurface1031">
                    <mesh
                      name="polySurface1031_aiStandardSurface10_0"
                      
                      
                      geometry={nodes.polySurface1031_aiStandardSurface10_0.geometry}
                      material={materials.aiStandardSurface10}
                    />
                  </group>
                  <group name="polySurface1032">
                    <mesh
                      name="polySurface1032_aiStandardSurface10_0"
                      
                      
                      geometry={nodes.polySurface1032_aiStandardSurface10_0.geometry}
                      material={materials.aiStandardSurface10}
                    />
                  </group>
                  <group name="polySurface1033">
                    <mesh
                      name="polySurface1033_aiStandardSurface10_0"
                      
                      
                      geometry={nodes.polySurface1033_aiStandardSurface10_0.geometry}
                      material={materials.aiStandardSurface10}
                    />
                  </group>
                  <group name="polySurface1034">
                    <mesh
                      name="polySurface1034_aiStandardSurface10_0"
                      
                      
                      geometry={nodes.polySurface1034_aiStandardSurface10_0.geometry}
                      material={materials.aiStandardSurface10}
                    />
                  </group>
                  <group name="polySurface1035">
                    <mesh
                      name="polySurface1035_aiStandardSurface10_0"
                      
                      
                      geometry={nodes.polySurface1035_aiStandardSurface10_0.geometry}
                      material={materials.aiStandardSurface10}
                    />
                  </group>
                </group>
                <group name="polySurface751" position={[-2.312, -162.744, -46.6]}>
                  <group name="polySurface920">
                    <mesh
                      name="polySurface920_aiStandardSurface13_0"
                      
                      
                      geometry={nodes.polySurface920_aiStandardSurface13_0.geometry}
                      material={materials.aiStandardSurface13}
                    />
                  </group>
                  <group name="polySurface921">
                    <mesh
                      name="polySurface921_aiStandardSurface13_0"
                      
                      
                      geometry={nodes.polySurface921_aiStandardSurface13_0.geometry}
                      material={materials.aiStandardSurface13}
                    />
                  </group>
                  <group name="polySurface922">
                    <mesh
                      name="polySurface922_aiStandardSurface13_0"
                      
                      
                      geometry={nodes.polySurface922_aiStandardSurface13_0.geometry}
                      material={materials.aiStandardSurface13}
                    />
                  </group>
                  <group name="polySurface936">
                    <mesh
                      name="polySurface936_aiStandardSurface13_0"
                      
                      
                      geometry={nodes.polySurface936_aiStandardSurface13_0.geometry}
                      material={materials.aiStandardSurface13}
                    />
                  </group>
                  <group name="polySurface950">
                    <mesh
                      name="polySurface950_aiStandardSurface13_0"
                      
                      
                      geometry={nodes.polySurface950_aiStandardSurface13_0.geometry}
                      material={materials.aiStandardSurface13}
                    />
                  </group>
                  <group name="polySurface958">
                    <mesh
                      name="polySurface958_aiStandardSurface13_0"
                      
                      
                      geometry={nodes.polySurface958_aiStandardSurface13_0.geometry}
                      material={materials.aiStandardSurface13}
                    />
                  </group>
                  <group name="polySurface959">
                    <mesh
                      name="polySurface959_aiStandardSurface13_0"
                      
                      
                      geometry={nodes.polySurface959_aiStandardSurface13_0.geometry}
                      material={materials.aiStandardSurface13}
                    />
                  </group>
                  <group name="polySurface969">
                    <mesh
                      name="polySurface969_aiStandardSurface13_0"
                      
                      
                      geometry={nodes.polySurface969_aiStandardSurface13_0.geometry}
                      material={materials.aiStandardSurface13}
                    />
                  </group>
                  <group name="polySurface970">
                    <mesh
                      name="polySurface970_aiStandardSurface13_0"
                      
                      
                      geometry={nodes.polySurface970_aiStandardSurface13_0.geometry}
                      material={materials.aiStandardSurface13}
                    />
                  </group>
                </group>
                <group name="polySurface699" position={[-2.312, -162.744, -46.6]}>
                  <group name="polySurface1004">
                    <mesh
                      name="polySurface1004_aiStandardSurface9_0"
                      
                      
                      geometry={nodes.polySurface1004_aiStandardSurface9_0.geometry}
                      material={materials.aiStandardSurface9}
                    />
                  </group>
                </group>
                <group name="polySurface1062">
                  <mesh
                    name="polySurface1062_aiStandardSurface10_0"
                    
                    
                    geometry={nodes.polySurface1062_aiStandardSurface10_0.geometry}
                    material={materials.aiStandardSurface10}
                  />
                </group>
                <group name="polySurface1065">
                  <mesh
                    name="polySurface1065_aiStandardSurface13_0"
                    
                    
                    geometry={nodes.polySurface1065_aiStandardSurface13_0.geometry}
                    material={materials.aiStandardSurface13}
                  />
                </group>
                <group name="polySurface989">
                  <mesh
                    name="polySurface989_aiStandardSurface9_0"
                    
                    
                    geometry={nodes.polySurface989_aiStandardSurface9_0.geometry}
                    material={materials.aiStandardSurface9}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  )
}


export default Island;
